[tools]
node = "lts"
uv = "latest"
"github:anttilinno/todo-calendar" = "latest"
"github:anttilinno/goto" = { version = "2.2.2", bin = "goto-bin" }
"github:letmutex/gitas" = "0.0.6"
pnpm = "10.27.0"
gitleaks = "latest"
trivy = "latest"
k6 = "latest"
